//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_bilet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBilet
    {
        public int BiletID { get; set; }
        public int EtkinlikID { get; set; }
        public Nullable<int> Ucret { get; set; }
    
        public virtual tblEtkinlik tblEtkinlik { get; set; }
    }
}
