//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_bilet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEtkinlik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEtkinlik()
        {
            this.tblBilet = new HashSet<tblBilet>();
        }
    
        public int EtkinlikID { get; set; }
        public string EtkinlikAdi { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public Nullable<int> BolgeNo { get; set; }
        public Nullable<System.DateTimeOffset> Tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBilet> tblBilet { get; set; }
        public virtual tblBolge tblBolge { get; set; }
    }
}
