//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_bilet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFatura()
        {
            this.tblSiparis = new HashSet<tblSiparis>();
        }
    
        public int FaturaNo { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public int OdemeTuruId { get; set; }
    
        public virtual tblOdemeTuru tblOdemeTuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSiparis> tblSiparis { get; set; }
    }
}
