//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_bilet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIletişimBilgileri
    {
        public int No { get; set; }
        public string TelefonNumarasi { get; set; }
        public string Adres { get; set; }
        public string kisiNo { get; set; }
        public string email { get; set; }
    
        public virtual tblIletişimBilgileri tblIletişimBilgileri1 { get; set; }
        public virtual tblIletişimBilgileri tblIletişimBilgileri2 { get; set; }
        public virtual tblIletişimBilgileri tblIletişimBilgileri11 { get; set; }
        public virtual tblIletişimBilgileri tblIletişimBilgileri3 { get; set; }
    }
}
