//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_bilet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKategori
    {
        public int KategoriID { get; set; }
        public int KategoriTuruId { get; set; }
    
        public virtual tblKategoriTuru tblKategoriTuru { get; set; }
    }
}
