//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_bilet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiparis
    {
        public int SiparisNo { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<int> ToplamTutar { get; set; }
        public Nullable<int> FaturaNo { get; set; }
        public Nullable<int> SiparisMiktari { get; set; }
        public Nullable<int> BiletID { get; set; }
    
        public virtual tblFatura tblFatura { get; set; }
    }
}
